encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("rnd/random", views.rnd, name="rnd"),
    path("crt/create", views.create, name="create"),
    path("edt/<str:title>", views.edit, name="edit"),
    path("<str:title>", views.entry, name="entry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import redirect, render
from django import forms

from . import util

import markdown
import random


class SearchForm(forms.Form):
    search = forms.CharField(label="Search")


class CreateForm(forms.Form):
    title = forms.CharField(label="Title:")
    markdownForm = forms.CharField(label="Markdown:", widget=forms.Textarea(attrs={
        'name': 'markdown',
        'rows': 30,
        'cols': 5
    }))

class EditForm(forms.Form):
    markdownForm = forms.CharField(label="", widget=forms.Textarea(attrs={
        'rows': 30,
        'cols': 5
    }))


def index(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data["search"]
            entryObject = util.get_entry(search)
            if entryObject == None:
                entries = util.list_entries()
                searchOutput = []

                for entry in entries:
                    if entry.lower().find(search.lower()) != -1:
                        searchOutput.append(entry)
                if len(searchOutput) > 0:
                    return render(request, "encyclopedia/search.html", {
                        "entries": searchOutput,
                        "title": search
                    })
                else:
                    return render(request, "encyclopedia/error.html")
            else:
                return redirect('wiki:entry', search)
        else:
            return redirect('wiki:index')
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries()
        })


def entry(request, title):
    entryObject = util.get_entry(title)
    if entryObject == None:
        return render(request, "encyclopedia/error.html")
    else:
        entryHTML = markdown.markdown(entryObject)
        return render(request, "encyclopedia/entry.html", {
            "title": title.lower(),
            "entry": entryHTML
        })


def create(request):
    if request.method == "POST":
        form = CreateForm(request.POST)
        if not form.is_valid():
            return redirect('wiki:index')
        createTitle = form.cleaned_data["title"]
        createMarkdown = form.cleaned_data["markdownForm"]
        if createTitle in util.list_entries():
            return render(request, "encyclopedia/error.html")
        util.save_entry(createTitle, createMarkdown)
        return redirect('wiki:entry', createTitle)
    else:
        return render(request, "encyclopedia/create.html", {
            "form": CreateForm()
        })


def rnd(request):
    return redirect('wiki:entry', random.choice(util.list_entries()))


def edit(request, title):
    if request.method == "POST":
        form = EditForm(request.POST)
        if not form.is_valid():
            return redirect('wiki:index')
        createMarkdown = form.cleaned_data["markdownForm"]
        util.save_entry(title, createMarkdown)
        return redirect('wiki:entry', title)
    else:
        form = EditForm(initial={'markdownForm': util.get_entry(title)})
        return render(request, "encyclopedia/edit.html", {
            "form": form,
            "title": title
        })

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create a New Page!</h1>
    <form action="{% url 'wiki:create'%}" method="post">
        {% csrf_token %}
        {{form}}
        <div>
            <input type="submit" value="Save">
        </div>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Edit {{title}} page</h1>
    <form action="{% url 'wiki:edit' title%}" method="post">
        {% csrf_token %}
        {{form}}
        <div>
            <input type="submit" value="Save">
        </div>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    <div>
        <a href="{% url 'wiki:edit' title%}">Edit This Page</a>
    </div>
    {{ entry | safe }}
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<h1>Error</h1>
<h2>That page does not yet exist!</h2>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:entry' entry%}">{{entry}}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:index'%}" method="post">
                    {% csrf_token %}
                    <label for="id_search">Search:</label>
                    <input type="text" name="search" required="" id="id_search">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:rnd' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia: Search Results
{% endblock %}

{% block body %}
    <h1>All Pages containing {{title}}</h1>
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:entry' entry%}">{{entry}}</a></li>
        {% endfor %}
    </ul>

{% endblock %}